### ISSUE TITLE
anykey trigger works before join button is pressed

### ISSUE THREAD

**Issue by weinventyou** [kyledemeule/channel2014#16]
2 things, actually: First, you can press any key and it will trigger the next clip, even before the join button is pressed. Secondly, I realized that the trigger should be limited to just the space bar, rather than any key, because if you're in the overlay text and you want to shift+click or command+click any of the links, it accidentally triggers the next clip.

**Comment by kyledemeule** [comment]
Got it. Will address.

**Comment by kyledemeule** [comment]
IMO space bar is generally used to pause something, you sure you want that to change the video?

Also: do you want pause/play functionality? Could be on spacebar, clicking the screen, etc...

**Comment by kyledemeule** [comment]
Anyway, what you asked for: https://github.com/kyledemeule/channel2014/commit/133026d36e397f41232f0e5051b0b8f7b7fbe985

**Comment by kyledemeule** [comment]
Fixed with https://github.com/kyledemeule/channel2014/commit/133026d36e397f41232f0e5051b0b8f7b7fbe985

**Comment by weinventyou** [comment]
Sorry to shift gears again, but I think that's a good idea. Space to pause,
right arrow to go to the next video - what you had done earlier, sorry.

No on clicking the screen, just because I could imagine someone trying to
click one of the buttons and then accidentally missing and pausing the
video. It sounds ridiculous but I "miss" all the time.
