### ISSUE TITLE
Add Favicon

### ISSUE THREAD

**Issue by kyledemeule** [kyledemeule/channel2014#17]
Site should have one I think.

**Comment by weinventyou** [comment]
Good idea, hadn't thought of that. I'll get at least a placeholder up tonight.

**Comment by weinventyou** [comment]
Added favicon in last pull request

**Comment by kyledemeule** [comment]
All good as of https://github.com/kyledemeule/channel2014/commit/c5953bbe44ffe67ddf1226d0a1ce7dcae8bd5d8d
