### ISSUE TITLE
Investigate CDN

### ISSUE THREAD

**Issue by kyledemeule** [kyledemeule/channel2014#19]
Amazon AWS might be fast enough, but a CDN might be better. It looks like [CloudFlare](https://www.cloudflare.com/plans) has a free plan with unlimited bandwidth.

**Comment by weinventyou** [comment]
I signed up for their free plan and it's set up and activated.

**Comment by kyledemeule** [comment]
Is there a way to add me to that account?

**Comment by weinventyou** [comment]
It doesn't currently support multiple users for a single account, but if
you want I could just create a new password that we could share.

**Comment by kyledemeule** [comment]
OK so Cloudfare doesn't work the way I expected. Let's stick with Amazon S3 for now, if performance is an issue Amazon offers a CDN called [CloudFront](http://aws.amazon.com/cloudfront/), we can look into that.
