### ISSUE TITLE
Info copy needs to be written

### ISSUE THREAD

**Issue by kyledemeule** [kyledemeule/channel2014#5]
Current info copy(i.e. what you see when you press "?") is all specific to conferencecall.biz. We will need new copy for this site.

**Comment by weinventyou** [comment]
Not sure how to assign this to myself but I'll take care of this one later this week.

**Comment by weinventyou** [comment]
Updated as part of last pull request. By the way, in the credits I made your name a link to your website, or at least to one of your websites. Please change the URL if there is another one you'd rather link to.

**Comment by kyledemeule** [comment]
Yup! All written.
