### ISSUE TITLE
Social/share buttons

### ISSUE THREAD

**Issue by kyledemeule** [kyledemeule/channel2014#6]
When clicking "?" we need:
- Facebook
- Twitter

Share buttons to be displayed/working.

**Comment by weinventyou** [comment]
Not sure how to assign this to myself but I'll take care of this one later this week.

**Comment by weinventyou** [comment]
I added social media in the last pull request but ran into a (probably very VERY simple) issue with the layout of it in the info-overlay panel.

**Comment by kyledemeule** [comment]
Yeah looks like this is done.
